apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      port: 8080
      targetPort: 8080